### ISSUE TITLE
Documentation: 

### ISSUE THREAD

**Issue by kappa95** [zhangty019/S3_DeformFDM#1]
Dear developers, I would like to ask you if and when it will be put a documentation in order to try it.

Thank you so much

**Comment by zhangty019** [comment]
Thanks for your attention, the updated ReadMe and Description will come soon after our presentation on the SIGGRAPH ASIA 2022.

**Comment by kappa95** [comment]
Great! I wait your update! Thank you so much.

Best regards

**Comment by zhangty019** [comment]
Please check the updated [README.md] for more details.

**Comment by kappa95** [comment]
Thank you so much! I have the following question about the first usage instruction. As in the article and documentation, you need a tetrahedron mesh geometry for slicing the model. But which kind of mesh files have this kind of meshing? For STL files that uses triangular meshes how can I manage?

Thank you so much!
