### ISSUE TITLE
Add extrusion values for waypoints output text files

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/S3_DeformFDM#10]
Today, your output waypoint files (in GCode folder) contains only the target point coords and tool orientation vectors (six values), but it would be very useful to identify travels, for example by adding an extrusion command for each line.

It would ease the analysis and then create linking / travel paths (retract, approach, etc) later on, even if I know the next "fabrication" step will generate a 'true' G-Code file.

**Comment by yvanblanchard** [comment]
Another interesting option would be to ask generating only boundary paths (not the zig-zag paths) for the slices.

**Comment by zhangty019** [comment]
Thanks for your suggestion. The calculation of extrusion and travel commands are mentioned in another project, please check this link (https://github.com/zhangty019/MultiAxis_3DP_MotionPlanning).
