### ISSUE TITLE
Support Generation for Stress Reinforcement 

### ISSUE THREAD

**Issue by moorjuli** [zhangty019/S3_DeformFDM#12]
Hey,

I would like to print a part that is 100% optimized for stress reinforcement (no support free and surface quality aspects). Therefore, often it is needed to have support structures printed. Is the process of support generation implemented in this project? And if not, what is your workflow on using support structures? I found [Support_Generation_for_Curved_RoboFDM](https://github.com/zhangty019/Support_Generation_for_Curved_RoboFDM#support_generation_for_curved_robofdm), but since there is no documentation for it, I don't really know how to use it. 
Thank you for the project and your help!

**Comment by zhangty019** [comment]
Please refer to the updated version, the ReadMe file is updated.

**Comment by moorjuli** [comment]
Thank you for the updated ReadMe over there!
