### ISSUE TITLE
Wrong deformation after inputting stress data

### ISSUE THREAD

**Issue by moorjuli** [zhangty019/S3_DeformFDM#13]
Hey,

I am able to import stress data in a result.txt file generated by FEA software similar to the example files. I now tried to verify if the data is loaded correct but the deformation seen in your program using only strength reinforcement is very different to the one I see in the FEA software. For example I have a bar model that I apply a simple tension in one direction to in FEA and when i load the results it shows torsion i your software. Can you give some information on which data is needed in the result file. You say it is principal element stress but in which sequence? And what is about the 7th value in the files? As far as i see it is not used in the software at all, right? There must be something wrong with my values there

Thank you for any help!

**Comment by zhangty019** [comment]
Hi, please check this figure, it is used to indicate the meaning of each line of the stress file.
![Meaning of the stree file](https://user-images.githubusercontent.com/54126247/234619109-e71c79ba-dda0-4b4e-a524-c0c088a791c0.png)

**Comment by moorjuli** [comment]
Working with Abaqus, do you export **Max. Principal** or **Max. Principal (Abs)**?

**Comment by moorjuli** [comment]
Working with Abaqus, do you export **Max. Principal** or **Max. Principal (Abs)**?

**Comment by moorjuli** [comment]
Okay, after some calculations with the example files, I am very sure that it is the Max. Principal and not the Max. Principal (Abs) that you use. Sorry for the confusion!
