### ISSUE TITLE
Build Error in windows

### ISSUE THREAD

**Issue by HUANG-Haolun** [zhangty019/S3_DeformFDM#15]
Hi Tianyu,
When I run the program, I meet this error, but no error during building.
![e790b57df74476937510d91177db0c2](https://github.com/zhangty019/S3_DeformFDM/assets/72869392/e02f50a4-fe65-4631-9177-20fcf305add3)
![48c99eb9e6121178d7651b3bc1de081](https://github.com/zhangty019/S3_DeformFDM/assets/72869392/09b514c8-330b-49c2-b9ef-fc48e016acb2)
Btw, Will you pulish a release version?

**Comment by HUANG-Haolun** [comment]
has been solved, thanks

**Comment by Lophitube** [comment]
> has been solved, thanks

Sorry, can you tell me how to fix the above problem? I'm having the same problem as yours but don't know how to fix it
