### ISSUE TITLE
Get Tool-Path

### ISSUE THREAD

**Issue by yubeilin** [zhangty019/S3_DeformFDM#16]
Why is it that after clicking the "Get Tool-Path" button, the program processes the bunny model and generates surface slices regardless of whether a model has been imported or not?
![image](https://github.com/zhangty019/S3_DeformFDM/assets/129928530/3cc5c4f7-fecc-40b6-adfc-70c5d9e57267)

**Comment by moorjuli** [comment]
You need to take a look at Step 4, which is described in readme. There is some remeshing that is done using a bat file outside the program. If you don't do that, the standard files in the remeshed folder will be read in Step 5, that's why you see the bunny.
