### ISSUE TITLE
Ankle test model

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/S3_DeformFDM#2]
Hello,

Could it be possible to get the Ankle data set, including original STEP geometry file (or at least obj mesh file), and 3D tet mesh (same as the one used in paper) ?
Thank you 
![image](https://user-images.githubusercontent.com/63931618/206763423-a0e9690a-1c40-48ae-98a8-f278c318dc6e.png)

**Comment by zhangty019** [comment]
Thanks for your attention, the relevant files have been uploaded to \DataSet\TET_MODEL, the model name is "AnkleBaseV1"
