### ISSUE TITLE
metal materials

### ISSUE THREAD

**Issue by chaiweifeng** [zhangty019/S3_DeformFDM#22]
Hello, may I ask if this algorithm is suitable for multi axis printing of metal materials by robots

**Comment by zhangty019** [comment]
Sure, the S^3-slicer is suitable for the extrusion-based printing method. For metal printing, it can be used for Wire Arc Additive Manufacturing (WAAM). However, please note that the slicing and toolpath generation will need some modifications to adapt to different applications.

**Comment by chaiweifeng** [comment]
Thank you for your answer. I would like to use robots to complete laser cladding and remanufacturing. Can this algorithm be applied to the melting process？   Looking forward to your answer，thanks！

**Comment by zhangty019** [comment]
If my understanding is correct, the technology you mentioned is DED (Direct energy deposition). The answer is yes, it is similar to the FDM.

**Comment by chaiweifeng** [comment]
Thank you for your patient answer. Your article is excellent and relevant to my research direction. I would like to delve deeper into learning and exploration.             Thank you again！
