### ISSUE TITLE
Error while running the batch file, translation from .off to .tet

### ISSUE THREAD

**Issue by mark-o-polo** [zhangty019/S3_DeformFDM#23]
Dear Zhang,

As of now I have taken the following steps:
Created a simple beam geometry in abaqus, meshed it, applied loads and ran the simulation.
Thereafter I extract the file in .obj format and import it in Meshlab so that it can then be translated and exported as a .off file.
Now this .off file is supposed to applied in the batch file as instructed, but  I get an error as depicted in the pictures presented.
Meaning that I cannot generate the .tet file since the step before that does not respond.

How would this particular issues be tackled best?

Thank you for your time!

![error2](https://github.com/zhangty019/S3_DeformFDM/assets/82767330/268e2f65-390e-4c46-991b-5e740927f11c)
![error1](https://github.com/zhangty019/S3_DeformFDM/assets/82767330/6a890bc3-09cf-4601-adfe-74fe24c1c436)

**Comment by zhangty019** [comment]
It seems the mesh quality is not good enough to generate the TET model from the OFF model, I suggest to remesh the OFF file and then generate the TET again until there is no warning like "Invilide PLC".

**Comment by beeekey** [comment]
how and where is the instruction to convert OFF to TET files?

**Comment by mark-o-polo** [comment]
@zhangty019 I unfortunately am still having problems with the usage of the slicer software. As can be seen here in the picture, I am unable to use 1.1-1.7 once I've imported the meshed and translated files. Why is that the case and are there any tips to get around it and successfully reinforce the volume imported?
![image](https://github.com/zhangty019/S3_DeformFDM/assets/82767330/5306d849-4103-4152-b948-da82af5e264e)

**Comment by zhangty019** [comment]
Please check the closed ISSUE 24 (https://github.com/zhangty019/S3_DeformFDM/issues/24), more information and the file generation in different types are mentioned, e,g, .tet model generation and FEA.
