### ISSUE TITLE
Documentation: This Repo has the potential to rule the further development of 3d printing

### ISSUE THREAD

**Issue by beeekey** [zhangty019/S3_DeformFDM#24]
I really think, this repo has the potential to rule the further development of 3d printing. There are several projects out there to  add several axis to existing printers or build 5 or 6 axis printers, but all lack of a slicer.

But the documentation is lacking of information. After several tries I was able to build  it successful on ubuntu. So it would be really cool to upgrade the documentation about building it.

But now, I honestly don't know what type of file I can open in the slicer and how to convert an OFF file to a TET file on ubuntu. I also don't know what files I can open in the slicer. I thought it can use STL, but now stumbled upon TET files.

Would it be possible to improve the documentation? I would like to include my workflow how I built it on ubuntu.

I'm sure, that you and the work you have done, can be the next step for the open source community to move to more axis.

Kind regards

**Comment by zhangty019** [comment]
Hi all, I wrote a note describing the total steps for the tetrahedron model generation and the stress field generation (input) for the strength reinforcement case. please check the attached instructions. 
[Generation of Stress field form Abaqus.docx](https://github.com/user-attachments/files/16445194/Generation.of.Stress.field.form.Abaqus.docx)
