### ISSUE TITLE
Fatal Error C1128: "number of sections exceeded object file format limit : compile with /bigobj"

### ISSUE THREAD

**Issue by moorjuli** [zhangty019/S3_DeformFDM#4]
Hey guys,

first of all thanks to the team for this amazing project, i can't wait to produce my first own prints based on S^3-Slicer. 
When trying to build the application on two different Windows System i ran into the same error stated above. 
The solution that worked for me was to add "/bigobj" to "Configuration Properties > C/C++ > Command Line > Additional Options" to the ShapeLab Property Page as shown below.
![image](https://user-images.githubusercontent.com/29074312/209108256-d28b3728-f3a4-4e08-a0ad-2618f4a4c4cb.png)
If this was a general error occuring on other systems as well, it might be useful to add this to the installation part of the documentation.

**Comment by zhangty019** [comment]
Thanks for your reminder, The related problem has been modified in the README.md
