### ISSUE TITLE
Question: which input file is compatible?

### ISSUE THREAD

**Issue by kappa95** [zhangty019/S3_DeformFDM#5]
Dear developers,

In the first usage step is not clear which kind of mesh files is compatible with this software. It is specified only tetrahedron meshes but common files for 3D printing are STL with triangular meshes.

How can I slice other objects?

Best regards

**Comment by zhangty019** [comment]
Thanks for your attention, our platform only supports tetrahedron mesh now. There are some software that can convert a surface mesh into tetrahedron mesh, e.g. tetgen (https://wias-berlin.de/software/tetgen/)
