### ISSUE TITLE
Exception thrown (Qt5Cored.dll) in ShapeLab.exe: Access violation reading location 

### ISSUE THREAD

**Issue by moorjuli** [zhangty019/S3_DeformFDM#6]
Hey,

i am able to access the gui without a problem, but when i try to open any of the example .tet files the following error occurs:
![image](https://user-images.githubusercontent.com/29074312/210365094-09c6f972-95fe-40e5-9144-fb144ca3f3dc.png)

Does anyone have an idea how to fix this or even has the same problem? Thank you for your help in advance.

Kind regard,
Julian

**Comment by zhangty019** [comment]
This means that there are no mesh entities in the list, could you describe in more detail how this issue is triggered?

**Comment by moorjuli** [comment]
I just rebuild the whole project and i am getting the same issue. I set everything up, just as it is described in readme and I am able interact with the UI. But when i click File>Open in the top left corner and try to open any of the example files i do get the error described above. I am using Visual Studio 2019 and the suggested Version of QT, all running on Windows 10.

**Comment by moorjuli** [comment]
![image](https://user-images.githubusercontent.com/29074312/211503422-26e41b4b-7281-4922-8435-1f884e3926bb.png)
Looking into the cmd everything looks allright

**Comment by hanbaiyi** [comment]
> Today i was able to reproduce the issue on two other systems, so this seems to be a general issue/bug. Any idea on how to fix this? Also i recognized that besides _oneAPI Math Kernel Library_ the _oneAPI DPC++/C++ Compiler_ is required, which could be added to the readme. Again thank you for your great work!

I also had the same problem, please how did you solve it

**Comment by zhangty019** [comment]
Please check whether it is caused by the MKL library configuration.

**Comment by moorjuli** [comment]
@hanbaiyi I sadly was not able to solve the problem yet.
@zhangty019 MKL Library is configured as described in the documentation. Could your share your detailed MKL Configuration?

**Comment by moorjuli** [comment]
Okay, I was able to fix the issue, thanks to the update made in the documentation. Thank you @zhangty019. Changing the code generation method to Multi-threaded Debug (/MTd) solved it for me @hanbaiyi.
