### ISSUE TITLE
Intel OneAPI MKL config not available in VS2017 and compile error 

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/S3_DeformFDM#8]
Hello,

I tried to follow recommendations by installing the Intel OneAPI MKL (I installed version 2023), but I can't active it in VS 2017 since I don't have the Intel MKL settings in the ShapeLab project config properties panel:
![image](https://user-images.githubusercontent.com/63931618/224952364-9f8445c2-e942-4fe9-a94f-c201c16bbda0.png)
nb: I also miss the MKL file paths in includes (c++ properties).

When compiling shapeLab project, I get errors with because of missing mkl_pardiso.h (used through eigen3), but maybe it's related to previous issue ?

Could you please indicate what's wrong or if it's a well-known issue ? which version of Intel MKL you used ?
 I'm using Win10.

Thank you

**Comment by zhangty019** [comment]
Hi, please check the updated ReadMe file to find the link for MKL downloading from Intel. and this is the screen capture of my environment for reference. Thanks.
![configure_capture](https://user-images.githubusercontent.com/54126247/225314477-b0059261-90b2-440e-b08a-9ec8a214ceaf.png)

**Comment by yvanblanchard** [comment]
Thank you @zhangty019 
But it was the same version I installed at my side (v2023).
After looking at the software prerequesites on Intel webpage (for this MKL component), it seems that only MS VisualStudio 2019 and 2022 are supported.
Since I'm using VS2017, maybe that's the problem.
Which VS version are you using (I saw 2017 on the ReadMe, but..)

**Comment by zhangty019** [comment]
I use the VS2019 on my pc. Maybe this is the reason.
![cofigure](https://user-images.githubusercontent.com/54126247/225331016-28077db6-a851-4b10-b5c7-f0806d7c13a9.png)

**Comment by yvanblanchard** [comment]
I installed VS2019, and I also had to reinstall MKL again but this time by asking to integrate with VS. And then everything is fine. 
Thank you again

![image](https://user-images.githubusercontent.com/63931618/225420337-6d4243e9-78be-47ef-aaa1-9ba4c9ba6a42.png)
