### ISSUE TITLE
New TetMesh model: selectionFilter file

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/S3_DeformFDM#9]
Hello,

I'm trying to use my own TetMesh model in your framework.
I modified the "updateFramewokParameter" method for my model name, but it now tried to load and read a corresponding "selectionFilter" text file.
The existing selectionFilter files contain chinese characters, so I can't try to understand which kind of data I have to define for my model (for creating my own selectionFilter).

Could you please help me with that ?
Thank you

**Comment by yvanblanchard** [comment]
I noticed that the content of those selectionFilter text file is not in Chinese when previewing them directly from GitHub.

**Comment by yvanblanchard** [comment]
@zhangty019 I tried to copy one of this selectionFilter file, renaming it with the name of my tetMesh file, for running the slicer, but processing hangs...
Could you please try by yourself, and tell me how to proceed (if succeed at your side) ? I share my TetMesh file (thing.tet).
Thank you
[thing-tetMesh.zip](https://github.com/zhangty019/S3_DeformFDM/files/11000214/thing-tetMesh.zip)

**Comment by yvanblanchard** [comment]
@zhangty019 Could you please help me on that point ? I'm stucked on this for the moment..

**Comment by zhangty019** [comment]
Hi @yvanblanchard, please check the attachment for details.
[Issue 9.zip](https://github.com/zhangty019/S3_DeformFDM/files/11029205/Issue.9.zip)

**Comment by yvanblanchard** [comment]
Thank you @zhangty019 
I will try that now.

Just some quick questions before:
- why do you have to select the (particular) face on the bottom ? Is it always the 'base' surface (on top of printing bed ?)
- in your memory image, it shows 100 GB of RAM consumption ? what is your computer config (memory size) at your side ? Do you think it would be possible to reduce the memory usage in the code (without too much efforts) ?
- you said that 8 Mb max for the tet mesh is required ? why this limit (for memory limits ?) the file I sent you had 12 Mb. How did you proceed for reducing the size (extracting skin mesh, then remeshing coarsly / uniformly, before refilling again ?) 


Sorry for the questions, but it's for better understanding at my side :
Thank you again for your help.

**Comment by yvanblanchard** [comment]
@zhangty019  I tried following your requirements, and it works much better now, thanks.
But new remarks:
- what is the exact purpose of this selection file ? (especially if it's not important to select the base area or the other mesh part)
- when clicking on toolpath button (5), the Bunny model was inserted and displayed in viewer !
![image](https://user-images.githubusercontent.com/63931618/226678705-58e99485-5a80-43a7-be4c-bdf4b40b36ff.png)
- I got errors when computing the toolpath (in console window:)
![image](https://user-images.githubusercontent.com/63931618/226678478-5d83dc6b-2c25-4ae5-a870-3a3c832da7e3.png)
- I got a crash (exception) when computing the 'Fabrication' (last tab-page)

**Comment by yvanblanchard** [comment]
I forgot to ask: 
you mentioned that the coordinate system (of input mesh model) was "Y up", and then modified (transformed to be "Z up" ?), but it seems my mesh (stl/obj, and then tet mesh) was 'Z up', in the expected printing direction (see image, blue line of coord sys is Z):
![image](https://user-images.githubusercontent.com/63931618/226750678-e4463e84-4127-4e37-a111-7f52a36c9019.png)

So why the need to modify/reorient it ?

thnak you again,

**Comment by zhangty019** [comment]
> @zhangty019 I tried following your requirements, and it works much better now, thanks. But new remarks:
> 
> * what is the exact purpose of this selection file ? (especially if it's not important to select the base area or the other mesh part)
> * when clicking on toolpath button (5), the Bunny model was inserted and displayed in viewer !
>   ![image](https://user-images.githubusercontent.com/63931618/226678705-58e99485-5a80-43a7-be4c-bdf4b40b36ff.png)
> * I got errors when computing the toolpath (in console window:)
>   ![image](https://user-images.githubusercontent.com/63931618/226678478-5d83dc6b-2c25-4ae5-a870-3a3c832da7e3.png)
> * I got a crash (exception) when computing the 'Fabrication' (last tab-page)

1. In the SQ (surface quality kept) case and other hybrid cases which include the SQ requirement, the selection file is needed to let the code know which part of the model surface should be kept.
2. Please refer to Step 4 of Usage in README, the layers should be remeshed before toolpath generation and they are saved into /DataSet/remesh_operation/layers_remeshed/
3. The warning means, in the small patch, there is not enough space to generate zigzag toolpaths after the 3-ring boundary. It is ok, some protection is done already.

**Comment by zhangty019** [comment]
> I forgot to ask: you mentioned that the coordinate system (of input mesh model) was "Y up", and then modified (transformed to be "Z up" ?), but it seems my mesh (stl/obj, and then tet mesh) was 'Z up', in the expected printing direction (see image, blue line of coord sys is Z): ![image](https://user-images.githubusercontent.com/63931618/226750678-e4463e84-4127-4e37-a111-7f52a36c9019.png)
> 
> So why the need to modify/reorient it ?
> 
> Could you also please share with me the new outer mesh (coarsy), that you used for the tet filler (and generate the new 'thing_updated.tet' file)?
> 
> Thank you again,

The deformation and bottom detection algorithm is using the Yup rules, and I transform them into Zup for the fabrication steps.

**Comment by yvanblanchard** [comment]
Ok , it's clear now. thanks a lot again
